version: '3'

services:
  asa-mod-update-notifier:
    build: .
    image: zalosath/asa-mod-update-notifier
    container_name: asa-mod-update-notifier
    env_file:
      - .env
    volumes:
      - ./scripts:/app
      - ./db:/db
    restart: no